### ISSUE TITLE
ENH: Add plot of new cases 7-day average

### ISSUE THREAD

**Issue by corneliusroemer** [micb25/RKI_Monkeypox#1]
Amazing that you extract the data!

Would be great to have 7d incidence or whatever one may want to call it.

Also, would be great to plot this on log scale 👼

**Comment by micb25** [comment]
Basic processing has been implemented and the corresponding data can be found in a separate [CSV file](https://github.com/micb25/RKI_Monkeypox/blob/main/data/RKI_Monkeypox_processed.csv). 

New/updated graphs are WIP 😉

**Comment by corneliusroemer** [comment]
I've meanwhile set up a datawrapper plot, processing in a Google Sheet :D 
https://www.datawrapper.de/_/hYizv/

**Comment by micb25** [comment]
These changes should improve the quality of this project significantly. Thanks a lot! 😀
